name: Deploy ERP to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deployment Scripts via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            cd /home/u465920647/domains/impostmedia.com/public_html/workspace || exit

            git pull origin main

            if [ ! -f "composer.json" ]; then
                echo "Error: File tidak ditemukan. Cek koneksi Git!"
                exit 1
            fi

            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force

            chmod -R 775 storage bootstrap/cache
