name: Deploy ERP Enterprise Edition (SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy-via-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Eksekusi Perintah di Server Hostinger via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd domains/impostmedia.com/public_html/workspace

            git pull origin main

            composer install --optimize-autoloader --no-dev --no-progress --no-interaction

            npm install
            npm run build

            php artisan migrate --force

            php artisan optimize:clear
            php artisan view:clear
            php artisan livewire:discover
