name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deployment Scripts via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            cd domains/impostmedia.com/public_html/workspace

            git pull origin main

            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Bersihkan dan buat ulang cache konfigurasi
            php artisan optimize:clear
            php artisan config:cache
            php artisan event:cache
            php artisan route:cache
            php artisan view:cache

            php artisan migrate --force

            # php artisan queue:restart
